# Generated by Django 3.0.5 on 2025-03-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0002_auto_20250310_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='change_given',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='machine',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
